package dev;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.zeroturnaround.zip.ZipUtil;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class App {
	public static void main(String[] args) { new App(); }
	
	private static final String mcMeta = " {\n" + 
										"  \"pack\": {\n" + 
										"    \"pack_format\": PACK_FORMAT,\n" + 
										"    \"description\": \"§9Version : §71.4.12\"\n" + 
										"  }\n" + 
										"}\n" + 
										"";
	
	private static final List<String> deleteItems = Arrays.asList("boat", "map", "compass", "clock", "banner", "bow", "leather", "slot", "potion", "tipped", "spectral", "enchanted", "nether_star", "spawn", "end_crystal", "gray_stained_glass_pane");
	private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
	private static final String comment = "Generated by LGRessource by Ekinoxx";
	
	private static final String assets = "assets\\minecraft";
	private static File generatedAssets;
	private static final File generatedFolder = new File("D:\\Files\\Scolaire\\workspace\\RessourcePackGenerator\\target\\generated\\");
	private static final File thisFolder = new File("D:\\Files\\Scolaire\\workspace\\RessourcePackGenerator\\src\\ressources\\");
	private static final String BASE_FOLDER = "C:\\Users\\Ekinoxx\\Desktop\\MultiMC\\instances\\";
	private static final String FOLDER_I = "\\.minecraft\\resourcepacks\\Default\\assets\\minecraft\\";
	private static final String VERSION = "1.9.4";
	private static final String specialName = "_specials";
	
	static {
		generatedAssets = new File(generatedFolder, assets);
	}
	
	private final File folderModelsItem;
	private final File folderTexturesItem;

	private final List<Material> available_models = new LinkedList<Material>();
	private final List<Material> available_textures = new LinkedList<Material>();
	private final List<String> items_models = new ArrayList<String>();
	private final List<String> items_textures = new ArrayList<String>();
	
	private String specialItemsEnum = "";
	private HashMap<String, HashMap<String, Material>> mapping = new HashMap<String, HashMap<String, Material>>();
	
	public App() {
		folderModelsItem = new File(BASE_FOLDER + VERSION + FOLDER_I + "models\\item");
		folderTexturesItem = new File(BASE_FOLDER + VERSION + FOLDER_I + "textures\\items");
		try {
			verify();
			fill();
			generate();
		} catch(Exception ex) {
			ex.printStackTrace();
		}
	}
	
	private void verify() throws IOException {
		if(generatedFolder.exists()) {
			FileUtils.deleteDirectory(generatedFolder);
		}
		generatedAssets.mkdirs();
		
		if(!thisFolder.exists()) {
			System.out.println("Wtf");
			return;
		}
		
		if (!folderModelsItem.exists() || !folderTexturesItem.exists()) {
			System.out.println("Folder doesn't exist for version : " + VERSION + " " + folderModelsItem.exists() + "/" +  folderTexturesItem.exists());
			return;
		}
	}
	
	private void fill() {
		System.out.println("Listing items model...");
		modelLoop:
		for (File itemModel : folderModelsItem.listFiles()) {
			for(String deleted : deleteItems)
				if(itemModel.getName().toLowerCase().contains(deleted.toLowerCase()))
					continue modelLoop;
			items_models.add(itemModel.getName().replace(".json", "").toLowerCase());
		}
		System.out.println("Registered " + items_models.size() + " items models.");

		System.out.println("Listing items textures...");
		textureLoop:
		for (File itemTexture : folderTexturesItem.listFiles()) {
			for(String deleted : deleteItems)
				if(itemTexture.getName().toLowerCase().contains(deleted.toLowerCase()))
					continue textureLoop;
			items_textures.add(itemTexture.getName().replace(".png", "").toLowerCase());
		}
		System.out.println("Registered " + items_textures.size() + " items textures.");
		System.out.println();
		
		int noMaterial = 0;
		for(String itemModel : new ArrayList<String>(items_models))
			if(Material.getMaterial(itemModel) == null) {
				noMaterial++;
				items_models.remove(itemModel);
			}
		
		System.out.println("Material reconnu pour " + items_models.size() + " models (" + noMaterial + " ignorés)");
		
		noMaterial = 0;
		
		for(String itemTexture : new ArrayList<String>(items_textures))
			if(Material.getMaterial(itemTexture) == null) {
				noMaterial++;
				items_textures.remove(itemTexture);
			}
		
		for(String itemModel : this.items_models)
			if(!available_models.contains(Material.getMaterial(itemModel)))
				available_models.add(Material.getMaterial(itemModel));

		available_models.sort(Comparator.comparing(Material::getPriority));
		Collections.reverse(available_models);
		
		for(String itemTexture : this.items_textures)
			if(!available_textures.contains(Material.getMaterial(itemTexture)))
				available_textures.add(Material.getMaterial(itemTexture));
		
		available_textures.sort(Comparator.comparing(Material::getPriority));
		Collections.reverse(available_textures);
		
		System.out.println("Material reconnu pour " + items_textures.size() + " textures (" + noMaterial + " ignorés)");
	}
	
	public Material getAvailableModel() throws IOException {
		Material m = available_models.remove(0);
		if(m == null) throw new IOException("No more material available !");
		available_textures.remove(m);
		return m;
	}
	
	public Material getAvailableTexture() throws IOException {
		Material m = available_textures.remove(0);
		if(m == null) throw new IOException("No more material available !");
		available_models.remove(m);
		return m;
	}
	
	private void generate() throws IOException {
		System.err.println("Don't forget to update LGSound if changed !");
		FileUtils.writeStringToFile(new File(generatedFolder, "pack.mcmeta"), mcMeta.replace("PACK_FORMAT", "5"));
		FileUtils.copyFile(new File(thisFolder, "pack.png"), new File(generatedFolder, "pack.png"));
		FileUtils.copyDirectory(new File(thisFolder, "sounds"), new File(generatedAssets, "sounds"));
		FileUtils.copyDirectory(new File(thisFolder, "textures/entity"), new File(generatedAssets, "textures/entity"));
		FileUtils.copyDirectory(new File(thisFolder, "textures/misc"), new File(generatedAssets, "textures/misc"));
		FileUtils.copyDirectory(new File(thisFolder, "textures/lg"), new File(generatedAssets, "textures/lg"));
		//Direct texturing
		specialItemsEnum += "	public static enum SpecialItems {\n";
		
		System.out.println("Génération des items spéciaux");
		mapping.put(specialName, new HashMap<String, Material>());
		List<File> specials = new ArrayList<File>();
		specials.addAll(Arrays.asList(new File(thisFolder, "textures/item/").listFiles()));
		specials.addAll(Arrays.asList(new File(thisFolder, "textures/lg/cards/").listFiles()));
		for(File texture : specials) {
			String name = texture.getName().replace(".png", "");
			if(name.contains(".")) throw new IOException("Invalid name : " + name + " in direct texturing item");
			specialItemsEnum += "		" + name.toUpperCase() + ",\n";
			Material m = getAvailableTexture();
			FileUtils.copyFile(texture, new File(generatedAssets, "textures/item/" + m.name().toLowerCase() + ".png"));
			mapping.get(specialName).put(name, m);
		}
		System.out.println(specials.size() + " direct texture générés (" + available_textures.size() + ")");
		
		//Model texturing
		FileUtils.copyDirectory(new File(thisFolder, "overlaymodel/"), new File(generatedAssets, "models/item/"));
		
		List<String> overlays = new ArrayList<String>();
		for(File f : new File(thisFolder, "overlaymodel/").listFiles())
			overlays.add(f.getName().replace(".json", ""));
		
		int fileRoleOverlayedNb = 0;
		for(File roleFile : new File(thisFolder, "textures/lg/roles/").listFiles()) {
			String roleName = roleFile.getName().replace(".png", "");
			mapping.put(roleName, new HashMap<String, Material>());
			for(String overlay : overlays) {
				String json = "{\n" + 
							"  \"parent\": \"item/" + overlay + "\",\n" + 
							"  \"textures\": {\n" + 
							"    \"role\": \"lg/roles/" + roleName + "\"\n" + 
							"  },\n" + 
							"  \"__comment\": \"" + comment + "\"\n" + 
							"}";
				Material m = getAvailableModel();
				mapping.get(roleName).put(overlay, m);
				FileUtils.writeStringToFile(new File(generatedAssets, "models/item/" + m.name().toLowerCase() + ".json"), json);
				fileRoleOverlayedNb++;
			}
			
			Material m = getAvailableTexture();
			FileUtils.copyFile(roleFile, new File(generatedAssets, "textures/item/" + m.name().toLowerCase() + ".png"));
			mapping.get(roleName).put("menu", m);
		}

		System.out.println(fileRoleOverlayedNb + " fichier rôle overlay générés");
		System.out.println("Il reste " + available_models.size() + " models disponible");
		System.out.println("Il reste " + available_textures.size() + " textures disponible");

		//Exporting all data json & java
		specialItemsEnum += "	}";
		FileUtils.writeStringToFile(new File(generatedFolder.getParentFile(), "specialItemsEnum.java"), specialItemsEnum);
		FileUtils.writeStringToFile(new File(generatedFolder.getParentFile(), "mapping_resource_pack.json"), GSON.toJson(mapping));
		
		File pre13 = new File(generatedFolder.getParentFile(), "pre-1-13/");
		FileUtils.copyDirectory(generatedFolder, pre13);
		File itemFolder = new File(pre13, assets + "\\textures\\item\\");
		FileUtils.copyDirectory(itemFolder, new File(pre13, assets + "\\textures\\items\\"));
		FileUtils.deleteDirectory(itemFolder);
		FileUtils.writeStringToFile(new File(pre13, "pack.mcmeta"), mcMeta.replace("PACK_FORMAT", "4"));
		
		//Success!
		System.out.println();
		System.out.println("Generated folder successfuly. Zipping it...");
		ZipUtil.pack(generatedFolder, new File(generatedFolder.getParentFile(), "generated.zip"));
		ZipUtil.pack(pre13, new File(generatedFolder.getParentFile(), "generated-pre13.zip"));
		FileUtils.deleteDirectory(pre13);
		FileUtils.deleteDirectory(generatedFolder);
		System.out.println("Ziiiiiipppppedd!");
	}

}
